# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build release version
      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          # Version to use (like '11.7', '12' or simply 'latest')
          version: latest
          # Whether to select a beta release or not. Beta releases may not always be available.
          beta: false

      - name: Xcode Archive
        uses: devbotsxyz/xcode-archive@v1.0.0
        with:
          configuration: Release

      - name: Xcode Export Archive
        uses: devbotsxyz/xcode-export-archive@v1.0.0
        with:
          # Export method (development, developer-id). Defaults to developer-id.
          export-method: developer-id
          export-path: "Export"

      - name: "Notarize Release Build"
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "Export/Keypad Layout.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
